### ISSUE TITLE
driver_matrix: Multi-stage pipeline tracking

### ISSUE THREAD

**Issue by k0machi** [scylladb/argus#289]
Currently, driver matrix tests rely on filename parsing to determine which test they are running. In addition to that, the submission happens at the end of pipeline, losing some of the potentially useful information - like start time, overall pipeline health is guessed instead.

The replacement mechanism should function akin to SCT and provide following features:

- [x] Maintain a unique job id per matrix run
- [x] Create an empty entity when a run is started
- [x] Submit each test result separately as they complete
- [ ] Use pipeline health indicator to provide general status - Failed, Passed, etc
- [x] Pass the test information (kind, driver) to the API.

**Comment by k0machi** [comment]
Better title and time estimation added.

**Comment by k0machi** [comment]
Current plans:

* Switching from docker container to a standalone client - assuming the `ec2-asg-x86` node pool we have has python 3.10
* Making a cli interface for the driver results - skipping need for a custom python script that has to be maintained separately
* Keeping legacy endpoint by checking schema version on the request
* The new API will contain this flow:
    * Create run - Requires UUID (pipeline manager) and build environment information (separate parameters, undecided which ones are needed). Run will be created with status "CREATED"
    * Submit result - Requires raw XML encoded as base64 inside the request json, as well as job id. First submission will set test status to "RUNNING" and apply heartbeat.
    * Fail result - Same as submit, probably under same command except different type, needs failure reason, run id. Won't change the status yet.
    * Finalize - Indicate that we have finished the pipeline. Backend will determine the results from that. Will need just the id.

**Comment by k0machi** [comment]
As a note, we will need to update all driver matrix repositories to generate some kind of metadata file, as the current implementation runs every version on the same process and only outputs results at the end, so we will need some way to collect which file belongs to which version.

**Comment by fruch** [comment]
@k0machi 

reopen this one, since we didn't finish the work for all of the matrixes,
please point from here to the PRs or other related work.

**Comment by fruch** [comment]
- Waiting on for rust
- and then update all of the pipelines

**Comment by k0machi** [comment]
All pipelines updated and all driver matrix repos received necessary changes.
